import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { existsSync } from 'node:fs'

import { parseFrontmatter } from '../core/lifecycle.js'
import { listAdrFiles } from '../core/repository-state.js'
import type { AdrConfig } from '../core/types.js'

export async function detectLegacyFrontmatter(
  repoRoot: string,
  config: Pick<AdrConfig['layout'], 'acceptedDir' | 'proposedDir'>,
): Promise<boolean> {
  for (const dir of [config.acceptedDir, config.proposedDir]) {
    const abs = path.join(repoRoot, dir)
    for (const name of await listAdrFiles(abs)) {
      const content = await readFile(path.join(abs, name), 'utf8')
      if (!parseFrontmatter(content).frontmatter) return true
    }
  }
  return false
}

export async function detectDocumentLanguage(repoRoot: string): Promise<'ja' | 'en'> {
  const contextPath = path.join(repoRoot, 'CONTEXT.md')
  if (existsSync(contextPath)) {
    const sample = (await readFile(contextPath, 'utf8')).slice(0, 4000)
    if (/[\u3040-\u30ff\u4e00-\u9faf]/.test(sample)) return 'ja'
  }

  const agentsPath = path.join(repoRoot, 'AGENTS.md')
  if (existsSync(agentsPath)) {
    const sample = (await readFile(agentsPath, 'utf8')).slice(0, 4000)
    if (/[\u3040-\u30ff\u4e00-\u9faf]/.test(sample)) return 'ja'
  }

  return 'en'
}

export function detectCiProvider(trackedFiles: string[]): 'github-actions' | null {
  if (trackedFiles.some((f) => f.startsWith('.github/workflows/'))) {
    return 'github-actions'
  }
  return null
}

export function ciWorkflowSuggestion(): string {
  return `# Generated by adr-governance — optional CI check
name: adr-governance
on:
  pull_request:
  push:
    branches: [main, develop]
jobs:
  adr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: node .adr-governance/bin/cli.mjs check --base origin/main
`
}
